-- DROP TYPE IF EXISTS tender_status;
-- DROP TYPE IF EXISTS tender_service_type;
-- DROP TYPE IF EXISTS author_type;
-- DROP TYPE IF EXISTS bid_status;
--
--
-- DROP TABLE IF EXISTS tender;
-- DROP TABLE IF EXISTS bid;
-- DROP TABLE IF EXISTS bid_history;
-- DROP TABLE IF EXISTS review;
